CREATE TABLE IF NOT EXISTS ai_feedback (id INTEGER PRIMARY KEY, article TEXT NOT NULL, type TEXT NOT NULL, agent TEXT NOT NULL, comment TEXT NOT NULL DEFAULT '', status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ai_feedback_quotas (quota_key TEXT PRIMARY KEY NOT NULL, count INTEGER NOT NULL);
